### ISSUE TITLE
default/global slugify options

### ISSUE THREAD

**Issue by blackspike** [nuxtclub/slugify#2]
Hi this works great in nuxt3 - quick q, is it possible to set global options? I'm using `$slugify(data.name, { lower: true, strict: true })` but I'd prefer to make that the global default. I tried adding a slugify options object to the config but no joy. cheers!

**Comment by imlautaro** [comment]
Now you can do it from the module settings. Anyway, I need to do more research on developing modules for Nuxt 3 because I still don't know how to migrate to Nuxt Kit.

**Comment by blackspike** [comment]
thank you so much! that works great and is much cleaner :)

**Comment by blackspike** [comment]
FYI I just updated nuxt from `3.0.0-rc.4` to `3.0.0-rc.6` and it now issues a warning

```
[warn] [nuxt] You are using a plugin with legacy Nuxt 2 format (context, inject) which is likely to be broken. In the future they will be ignored: (_, inject) => {



        inject('slugify', (string, options) => {
                return __vite_ssr_import_1__.default(
                        string, 
                        { 
                                ...JSON.parse('{"lower":true,"strict":true}'),
                                ...options, 
                        }
                )
        })
}
```

**Comment by imlautaro** [comment]
@blackspike I made a new module from scratch to learn and practice with Nuxt Kit. Try uninstalling this module and installing the new one: [nuxt-slugify](https://github.com/nuxtclub/nuxt-slugify). If you have any problem just let me know 👌

**Comment by blackspike** [comment]
Oh great! Hmm it installs and works fine, except it's not always respecting my global lowercase settings ?
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/4052525/180751791-aa680afd-e4c3-436b-8265-148d34ef6b68.png">

**Comment by imlautaro** [comment]
Ok, I will try to fix that problem in a moment.  Thanks for your feedback!

**Comment by imlautaro** [comment]
@blackspike Hmm, I'm trying that but it works fine for me. Can you show me how you are using the $slugify function?

**Comment by blackspike** [comment]
oh! my bad, I was just getting you code and I realised the heading that was correct was `h3.meta__title {{ $slugify(data.name) }}` and the dropdown that was incorrect was `span.results__name {{ slugify(item.name) }}` – I'd missed the $ on the incorrect one, and while it was slugged, it wasn't lowercase, mystery solved! Many thanks :)

**Comment by imlautaro** [comment]
Oh, anyway did an update fixing an issue with typescript and also added a composable `useSlugify` to use in the script.

**Comment by blackspike** [comment]
nice! how do you use useSlugify?

<img width="415" alt="image" src="https://user-images.githubusercontent.com/4052525/180765029-b48185ec-b329-4a05-a048-a02bb5945239.png">

**Comment by imlautaro** [comment]
Check the Readme in the new module repository

**Comment by blackspike** [comment]
oh yeah. That works great, I've updated my project to useSlugify throughout. Thanks a million !

**Comment by imlautaro** [comment]
Cool! Thanks a lot for your feedback too. If you have any suggestion for a module just let me know :)

**Comment by blackspike** [comment]
Me again! Just installed it (`"nuxt-slugify": "^1.1.0",`) on my other laptop and it's throwing this error 

I've cleared the npm cache, deleted and re-installed etc. Any ideas?

`Uncaught SyntaxError: import not found: default` in `http://localhost:3000/_nuxt/node_modules/nuxt-slugify/dist/runtime/plugin.mjs`

And in that file
```
import { defineNuxtPlugin, useRuntimeConfig } from "/_nuxt/@id/virtual:nuxt:/Users/xxx/.nuxt/imports.mjs";
import slugify from "/_nuxt/node_modules/slugify/slugify.js?v=373d7f60";
export default defineNuxtPlugin(() => {
  const {
    slugify: { extend, defaults }
  } = useRuntimeConfig();
  if (Object.keys(extend).length) {
    slugify.extend(extend);
  }
  return {
    provide: {
      slugify: (string, options) => {
        if (typeof options === "string") {
          options = {
            replacement: options
          };
        }
        return slugify(string, { ...defaults, ...options });
      }
    }
  };
});

```

![image](https://user-images.githubusercontent.com/4052525/180865913-2eab7497-5579-486f-b2e6-eb56272799b0.png)
